### ISSUE TITLE
having an issue with sub directories and pages not named index.md

### ISSUE THREAD

**Issue by adampotocki** [coexec/pico_admin#1]
Great plugin but it doesn't seem to be working correctly on my machine, the admin panel doesn't show the content for pages that are not named index.md. For example on a fresh install of pico  /content/sub/page.md is not able to be shown in markdown editor and when previewed goes to /sub/pageindex instead of /sub/page/

Screenshot:
![pico admin](https://cloud.githubusercontent.com/assets/2486725/6620232/06a6e108-c8a6-11e4-904b-231099a25ad8.png)

Thanks for your help!

**Comment by kstenschke** [comment]
Hi Adam, thanks for the feedback!
I also noticed this issue in the meanwhile. I will have to have a look into this soon. -If you happen to come along the solution before me, i'll be happy to receive a pull request also.

**Comment by kstenschke** [comment]
Hi Adam, this issue should be fixed now. please let me know if the solution also works for your environment. regards, Kay

**Comment by adampotocki** [comment]
Working great! Thank you so much!

**Comment by kstenschke** [comment]
you're welcome, thanks for your feedback :) i haven't tested all different file operations (eg. creation, delete) on different environments yet, so i recommend watching the repo. for updates.
